apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xd7dqkt6r-python 
  janus-idp.io/tekton: xd7dqkt6r-python
  backstage.io/kubernetes-id: xd7dqkt6r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xd7dqkt6r-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml