apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xd7dqkt6r-python
  janus-idp.io/tekton: xd7dqkt6r-python
  backstage.io/kubernetes-id: xd7dqkt6r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xd7dqkt6r-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
